-- Categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  count INTEGER DEFAULT 0,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  category TEXT,
  category_id BIGINT REFERENCES categories(id),
  badge TEXT,
  rating NUMERIC DEFAULT 0,
  reviews INTEGER DEFAULT 0,
  stock INTEGER DEFAULT 0,
  image TEXT,
  colors TEXT[],
  sizes TEXT[],
  description TEXT,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Testimonials table
CREATE TABLE testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  avatar TEXT,
  rating INTEGER DEFAULT 5,
  text TEXT NOT NULL,
  product TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Blog posts table
CREATE TABLE blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  image TEXT,
  category TEXT,
  read_time TEXT,
  author TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Customers table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Orders table
CREATE TABLE orders (
  id TEXT PRIMARY KEY, -- Using #VT-1042 format
  customer_id BIGINT REFERENCES customers(id),
  customer_name TEXT, -- Fallback
  customer_email TEXT, -- Fallback
  amount NUMERIC NOT NULL,
  items_count INTEGER NOT NULL,
  items JSONB NOT NULL,
  status TEXT DEFAULT 'processing',
  shipping_address JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Coupons table
CREATE TABLE coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  value TEXT NOT NULL,
  times_used INTEGER DEFAULT 0,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Row Level Security (RLS) Settings
-- For simplicity in this demo, we'll allow all roles to read, but you should restrict this in production.
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-only access" ON categories FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access" ON products FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Allow public read-only access" ON blog_posts FOR SELECT USING (true);

-- Admin policies (assuming service role or authenticated admin)
-- In a real scenario, you'd check for an 'admin' role in auth.users
CREATE POLICY "Allow all access to authenticated users" ON categories FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON products FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON testimonials FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON blog_posts FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON customers FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON orders FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all access to authenticated users" ON coupons FOR ALL TO authenticated USING (true);
